### ISSUE TITLE
Scan only for BLE

### ISSUE THREAD

**Issue by kappelloss** [schollz/find3-cli-scanner#11]
Is their a way to only scan for BLE and not for Wifi?

**Comment by danpowpow** [comment]
+1

**Comment by schollz** [comment]
@kappelloss @danpowpow Currently now. It should be easy to do, please make a PR!

**Comment by schollz** [comment]
You can now, with `-bluetooth`: https://github.com/schollz/find3-cli-scanner/commit/b2f6fc9496948471a9997c7b89c6c24fa8873055
