### ISSUE TITLE
Building docker image failed

### ISSUE THREAD

**Issue by kappelloss** [schollz/find3-cli-scanner#17]
root@raspberrypi:~/image# docker build -t schollz/find3-cli-scanner .
Sending build context to Docker daemon   5.12kB
Step 1/5 : FROM ubuntu:18.04
 ---> ec875438e96e
Step 2/5 : ENV GOLANG_VERSION 1.10
 ---> Using cache
 ---> d6ce35af5074
Step 3/5 : ENV PATH="/usr/local/go/bin:${PATH}"
 ---> Using cache
 ---> e0ff002d27f6
Step 4/5 : ENV GOPATH /root/go
 ---> Using cache
 ---> 3a6d0768f556
Step 5/5 : RUN apt-get update &&        DEBIAN_FRONTEND=noninteractive apt-get i                 nstall -y libc6-dev make pkg-config g++ gcc git wget wireless-tools bluetooth iw                  net-tools tshark &&    mkdir /root/go &&       rm -rf /var/lib/apt/lists/* && s                 et -eux;                dpkgArch="$(dpkg --print-architecture)";        case "${                 dpkgArch##*-}" in               amd64) goRelArch='linux-amd64'; goRelSha256='b5a                 64335f1490277b585832d1f6c7f8c6c11206cba5cd3f771dcb87b98ad1a33' ;;              a                 rmhf) goRelArch='linux-armv6l'; goRelSha256='6ff665a9ab61240cf9f11a07e03e6819e45                 2a618a32ea05bbb2c80182f838f4f' ;;               arm64) goRelArch='linux-arm64';                  goRelSha256='efb47e5c0e020b180291379ab625c6ec1c2e9e9b289336bc7169e6aa1da43fd8' ;                 ;               i386) goRelArch='linux-386'; goRelSha256='2d26a9f41fd80eeb445cc4                 54c2ba6b3d0db2fc732c53d7d0427a9f605bfc55a1' ;;          ppc64el) goRelArch='linu                 x-ppc64le'; goRelSha256='a1e22e2fbcb3e551e0bf59d0f8aeb4b3f2df86714f09d2acd260c65                 97c43beee' ;;           s390x) goRelArch='linux-s390x'; goRelSha256='71cde197e50                 afe17f097f81153edb450f880267699f22453272d184e0f4681d7' ;;               *) goRel                 Arch='src'; goRelSha256='f3de49289405fda5fd1483a8fe6bd2fa5469e005fd567df64485c4f                 a000c7f24';                     echo >&2; echo >&2 "warning: current architectur                 e ($dpkgArch) does not have a corresponding Go binary release; will be building                  from source"; echo >&2 ;;       esac;           url="https://golang.org/dl/go${G                 OLANG_VERSION}.${goRelArch}.tar.gz";    wget -O go.tgz "$url";  echo "${goRelSha                 256} *go.tgz" | sha256sum -c -;         tar -C /usr/local -xzf go.tgz;  rm go.tg                 z;              if [ "$goRelArch" = 'src' ]; then               echo >&2;      e                 cho >&2 'error: UNIMPLEMENTED';                 echo >&2 'TODO install golang-an                 y from jessie-backports for GOROOT_BOOTSTRAP (and uninstall after build)';     e                 cho >&2;                exit 1;         fi;             export PATH="/usr/local/                 go/bin:$PATH";  go version &&   go get -v github.com/schollz/find3-cli-scanner &                 &       cd /root/go/src/github.com/schollz/find3-cli-scanner && go build -v && m                 v find3-cli-scanner /usr/local/bin/ &&  echo "removing go srces" && rm -rf /usr/                 local/work/src &&       echo "purging packages" && apt-get remove -y --auto-remo                 ve git libc6-dev pkg-config g++ gcc make &&     echo "autoclean" && apt-get auto                 clean &&        echo "clean" && apt-get clean &&        echo "autoremove" && apt                 -get autoremove &&      echo "rm trash" && rm -rf ~/.local/share/Trash/* &&    e                 cho "rm go" && rm -rf /usr/local/go* &&         echo "rm go" && rm -rf /root/go*                  &&     echo "rm perl" && rm -rf /usr/share/perl* &&    echo "rm doc" && rm -rf                  /usr/share/doc*
 ---> Running in ab9c1dd4fba9
The command '/bin/sh -c apt-get update &&       DEBIAN_FRONTEND=noninteractive a                 pt-get install -y libc6-dev make pkg-config g++ gcc git wget wireless-tools blue                 tooth iw net-tools tshark &&    mkdir /root/go &&       rm -rf /var/lib/apt/list                 s/* &&  set -eux;               dpkgArch="$(dpkg --print-architecture)";       c                 ase "${dpkgArch##*-}" in                amd64) goRelArch='linux-amd64'; goRelSha                 256='b5a64335f1490277b585832d1f6c7f8c6c11206cba5cd3f771dcb87b98ad1a33' ;;      a                 rmhf) goRelArch='linux-armv6l'; goRelSha256='6ff665a9ab61240cf9f11a07e03e6819e45                 2a618a32ea05bbb2c80182f838f4f' ;;               arm64) goRelArch='linux-arm64';                  goRelSha256='efb47e5c0e020b180291379ab625c6ec1c2e9e9b289336bc7169e6aa1da43fd8' ;                 ;               i386) goRelArch='linux-386'; goRelSha256='2d26a9f41fd80eeb445cc4                 54c2ba6b3d0db2fc732c53d7d0427a9f605bfc55a1' ;;          ppc64el) goRelArch='linu                 x-ppc64le'; goRelSha256='a1e22e2fbcb3e551e0bf59d0f8aeb4b3f2df86714f09d2acd260c65                 97c43beee' ;;           s390x) goRelArch='linux-s390x'; goRelSha256='71cde197e50                 afe17f097f81153edb450f880267699f22453272d184e0f4681d7' ;;               *) goRel                 Arch='src'; goRelSha256='f3de49289405fda5fd1483a8fe6bd2fa5469e005fd567df64485c4f                 a000c7f24';                     echo >&2; echo >&2 "warning: current architectur                 e ($dpkgArch) does not have a corresponding Go binary release; will be building                  from source"; echo >&2 ;;       esac;           url="https://golang.org/dl/go${G                 OLANG_VERSION}.${goRelArch}.tar.gz";    wget -O go.tgz "$url";  echo "${goRelSha                 256} *go.tgz" | sha256sum -c -;         tar -C /usr/local -xzf go.tgz;  rm go.tg                 z;              if [ "$goRelArch" = 'src' ]; then               echo >&2;      e                 cho >&2 'error: UNIMPLEMENTED';                 echo >&2 'TODO install golang-an                 y from jessie-backports for GOROOT_BOOTSTRAP (and uninstall after build)';     e                 cho >&2;                exit 1;         fi;             export PATH="/usr/local/                 go/bin:$PATH";  go version &&   go get -v github.com/schollz/find3-cli-scanner &                 &       cd /root/go/src/github.com/schollz/find3-cli-scanner && go build -v && m                 v find3-cli-scanner /usr/local/bin/ &&  echo "removing go srces" && rm -rf /usr/                 local/work/src &&       echo "purging packages" && apt-get remove -y --auto-remo                 ve git libc6-dev pkg-config g++ gcc make &&     echo "autoclean" && apt-get auto                 clean &&        echo "clean" && apt-get clean &&        echo "autoremove" && apt                 -get autoremove &&      echo "rm trash" && rm -rf ~/.local/share/Trash/* &&    e                 cho "rm go" && rm -rf /usr/local/go* &&         echo "rm go" && rm -rf /root/go*                  &&     echo "rm perl" && rm -rf /usr/share/perl* &&    echo "rm doc" && rm -rf                  /usr/share/doc*' returned a non-zero code: 139

**Comment by schollz** [comment]
What kind of Raspberry Pi are you using? How much memory do you have? Docker doesn't have enough memory to build things on Pi Zero, and maybe others.

**Comment by kappelloss** [comment]
I am using a Pi Zero W...
