### ISSUE TITLE
install nativelly errors

### ISSUE THREAD

**Issue by fballan93** [schollz/find3-cli-scanner#38]
I keep getting 
go: cannot find main module; see 'go help modules'

whenever trying to install the cli on raspberry Pi
GO111MODULE=on go get -v github.com/schollz/find3-cli-scanner/v3
and whenever i open the github account it is not there

**Comment by schollz** [comment]
Whats your go version

`go env`

**Comment by fballan93** [comment]
thank you for your reply . this is my go env 

GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build461391806=/tmp/go-build -gno-record-gcc-switches"

**Comment by schollz** [comment]
And what is the output of the go get -v command?

**Comment by fballan93** [comment]
showing me the old error still. even after turning off the module . however i installed it from the source and run the go get-v command and worked perfectly . the github link is not working
