### ISSUE TITLE
Running the docker CLI with costume host gave errors 

### ISSUE THREAD

**Issue by fballan93** [schollz/find3-cli-scanner#39]
Hey ,

So I had a problem with running the cli nativaly so i switched to the docker method however whenever I want to insert a costume host into the run command :+1: 
sudo docker run --net="xyz.westeurope.cloudapp.azure.com" --privileged --name scannerr -d -i -t schollz/find3-cli-scanner

it would give me :+1: 
d5ff234311386abec67f71e6beaa5c0fb91583c0514e7fb2b3c02835c7cf7286
docker: Error response from daemon: network xyz.westeurope.cloudapp.azure.com not found.

even when adding https:// still it gives me the same error . kindly note that my find program is up and running with full functionality on that link . so I dont know what is the proper formatting of the command

**Comment by schollz** [comment]
net should be "host"

**Comment by fballan93** [comment]
So after working everything smoothly . and i have this custome command still i receive this error
