### ISSUE TITLE
Cannot launch find3-cli-scanner from Mac OSX

### ISSUE THREAD

**Issue by phadkead** [schollz/find3-cli-scanner#4]
I followed all the steps from https://www.internalpositioning.com/doc/tracking_your_computer.md and I am trying to launch find3-cli-scanner from docker instance, but it gives following exception:
```
2018-03-27 02:00:14 [INFO] main.go main:76 scanning with en0
2018-03-27 02:00:14 [ERROR] utils.go RunCommand:40 exit status 1: /sbin/iw dev en0 scan -u
2018-03-27 02:00:15 [ERROR] main.go basicCapture:164 json: cannot unmarshal number into Go value of type main.Response
```
Looks like docker image is not able to access wifi. Inside docker image:

```
root@linuxkit-025000000001:/# iwconfig
tunl0     no wireless extensions.
lo        no wireless extensions.
ip6tnl0   no wireless extensions.
docker0   no wireless extensions.
eth0      no wireless extensions.

```
Is there any workaround to run the scanner from Mac OSX?

**Comment by phadkead** [comment]
Yes I can see the same output for command
`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s`

I am not sure about command line utility for Bluetooth in OSX though

**Comment by schollz** [comment]
@phadkead It should now work natively on OS X
