### ISSUE TITLE
Raspberry Pi Zero W - cannot build project from binary

### ISSUE THREAD

**Issue by nash-stokes** [schollz/find3-cli-scanner#40]
Getting this output from terminal when running "sudo make" inside of directory. Made sure mage is installed and functional. Also installed preliminary dependency installs (including package referenced at the end of the output). Is this project supported on this device?

go get github.com/magefile/mage 
mage
fatal: not a git repository (or any of the parent directories): .git
go build -ldflags '-s -w -X main.version=dev'# _/home/pi/Projects/find3-cli-scanner-3.3.2
./main.go:54:14: cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignment
./main.go:61:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:65:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:69:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:74:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:79:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:84:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:89:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:94:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:98:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:98:15: too many errors
You may need to install libpcap.

OS X: brew install libpcap

Linux: apt-get install libpcap-dev

Error: running "go build -ldflags -s -w -X main.version=dev" failed with exit code 2
make: *** [Makefile:8: basicbuild] Error 2

**Comment by schollz** [comment]
Try just `go build -v`

**Comment by nash-stokes** [comment]
Thanks for getting back to me. Error output that I get after trying that command : 

_/home/pi/Projects/find3-cli-scanner-3.3.2
_/home/pi/Projects/find3-cli-scanner-3.3.2
./main.go:54:14: cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignment
./main.go:61:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:65:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:69:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:74:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:79:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:84:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:89:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:94:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:98:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./main.go:98:15: too many errors

**Comment by schollz** [comment]
Yeah, I think you need to use `GO111MODULE=on`. Try

`GO111MODULE=on go build -v`

**Comment by nash-stokes** [comment]
I think the error may have been in my version of Go. I also had to manually install yaml and run the command `syscall: implement rawVforkSyscall for linux/arm64`. Thanks for the help!
