### ISSUE TITLE
Errors installing on Raspbian Lite Pi 3b+

### ISSUE THREAD

**Issue by OliPassey** [schollz/find3-cli-scanner#45]
Installed go via apt-get
Rebooted
Tried to install cli scanner and get the below error.
Cant progress beyond this. Any advice?
Had this working previously, but have started with fresh installs after recieving two usb wifi adapters capable of monitor mode.

pi@raspberrypi:~ $ go get -u -v github.com/schollz/find3-cli-scanner
github.com/schollz/find3-cli-scanner (download)
github.com/cihub/seelog (download)
github.com/google/gopacket (download)
github.com/montanaflynn/stats (download)
github.com/schollz/find3 (download)
github.com/schollz/gatt (download)
github.com/schollz/wifiscan (download)
github.com/schollz/logger (download)
github.com/urfave/cli (download)
github.com/cpuguy83/go-md2man (download)
github.com/schollz/find3-cli-scanner
# github.com/schollz/find3-cli-scanner
go/src/github.com/schollz/find3-cli-scanner/main.go:54:14: cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignment
go/src/github.com/schollz/find3-cli-scanner/main.go:61:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:65:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:69:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:74:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:79:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:84:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:89:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:94:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:98:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/schollz/find3-cli-scanner/main.go:98:15: too many errors

**Comment by OliPassey** [comment]
Retried on full raspbian, same problem.
Saw your post re: GO111MODULE=on go get -v github.com/schollz/find3-cli-scanner/v3 
But i get:
go: cannot find main module; see 'go help modules'

Tried
go get -v github.com/schollz/find3-cli-scanner/v3

but got
github.com/schollz/find3-cli-scanner (download)
package github.com/schollz/find3-cli-scanner/v3: cannot find package "github.com/schollz/find3-cli-scanner/v3" in any of:
        /usr/lib/go-1.11/src/github.com/schollz/find3-cli-scanner/v3 (from $GOROOT)
        /home/pi/go/src/github.com/schollz/find3-cli-scanner/v3 (from $GOPATH)

**Comment by nash-stokes** [comment]
When you use the command "go version", what is outputted?

**Comment by OliPassey** [comment]
im on on go version go1.11.6 linux/arm
tried to upgrade to latest but doesnt seem to have worked.

**Comment by nash-stokes** [comment]
The thing that worked for me was using ```wget golang.org/dl/go1.14.1.linux-armv6l.tar.gz``` then following the rest of these instructions https://golang.org/doc/install?download=go1.14.1.linux-armv6l.tar.gz. After modifying $HOME/.profile, I then rebooted the pi. I would do this on a fresh install of raspbian. I didn't write the test program, but you want it to say go1.14.1 when you type ```go version```

**Comment by OliPassey** [comment]
Thanks, i'll give that a shot!

**Comment by OliPassey** [comment]
That got me going again, thank you!
Now, trying to get raspbian to show the USB wifi adapter :)
